# Atharva Jagtap

## Research question/interests

Briefly describe your research question or interests here.

In [ ]:
import pandas as pd

In [ ]:
data1 = pd.read_csv("C:\\Users\\athar\\Documents\\COSC 301\\project-group41\\data\\raw\\2015.csv")
data1

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,154,3.465,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,155,3.340,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,156,3.006,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,157,2.905,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,158,2.839,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [ ]:
data2 = pd.read_csv("C:\\Users\\athar\\Documents\\COSC 301\\project-group41\\data\\raw\\2016.csv")
data2

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,4,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,5,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...
152,Benin,153,3.484,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,154,3.360,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,155,3.303,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,156,3.069,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,157,2.905,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [ ]:
data3 = pd.read_csv("C:\\Users\\athar\\Documents\\COSC 301\\project-group41\\data\\raw\\2017.csv")
data3

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Norway,1,7.537,1.61646,1.53352,0.79667,0.63542,0.31596,0.36201,2.27703
1,Denmark,2,7.522,1.48238,1.55112,0.79257,0.62601,0.40077,0.35528,2.31371
2,Iceland,3,7.504,1.48063,1.61057,0.83355,0.62716,0.15353,0.47554,2.32272
3,Switzerland,4,7.494,1.56498,1.51691,0.85813,0.62007,0.36701,0.29055,2.27672
4,Finland,5,7.469,1.44357,1.54025,0.80916,0.61795,0.38261,0.24548,2.43018
...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,0.36875,0.94571,0.32642,0.58184,0.45522,0.25276,0.54006
151,Syria,152,3.462,0.77715,0.39610,0.50053,0.08154,0.15135,0.49366,1.06157
152,Tanzania,153,3.349,0.51114,1.04199,0.36451,0.39002,0.06604,0.35426,0.62113
153,Burundi,154,2.905,0.09162,0.62979,0.15161,0.05990,0.08415,0.20444,1.68302
154,Central African Republic,155,2.693,0.00000,0.00000,0.01877,0.27084,0.05657,0.28088,2.06600